import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "El Dolcet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className={`antialiased`}>
        <header className="h-12">
          <h1>
            <Link href={"/"}>El dolcet</Link>
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
