import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "El Dolcet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`antialiased h-full`}>{children}</body>
    </html>
  );
}
